FROM gitpod/openvscode-server
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - \
&& sudo apt update \
&& sudo apt install -y \
bash-completion \
curl \
gawk \
gcc \
g++ \
make \
nodejs \
postgresql-client \
unzip \
wget \
&& sudo rm -rf /var/lib/apt/lists/*
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
&& unzip -q awscliv2.zip \
&& sudo ./aws/install \
&& rm awscliv2.zip \
&& rm -rf ./aws
RUN git clone --recursive https://github.com/akinomyoga/ble.sh.git \
&& make -C ble.sh install PREFIX=~/.local \
&& echo 'source ~/.local/share/blesh/ble.sh' >> ~/.bashrc
